server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:x3akqrtww}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: stocks
        show_sql: true
        use_sql_comments: true
        format_sql: true
    show-sql: true